name: Portfolio Changes

on:
  push:
  schedule:
    - cron: "30,55 * * * *"

jobs:
  Portfolio_Changes:
    runs-on: ubuntu-latest
    steps:
      - name: readme2tex-action
        uses: montali/readme2tex-action@1.1

      - name: ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}.
        run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

      - name: Check out repository code.
        uses: actions/checkout@v2

      - name: ğŸ” List files in the repository.
        run: |
          ls ${{ github.workspace }}

      - name: ğŸ This job's status is ${{ job.status }}.
        run: echo "ğŸ This job's status is ${{ job.status }}."

      - name: ğŸ•› Checking the time of this Action.
        run: date

      # - name: Update README.md
      #   run: python Update.py